version: "3.3"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: 'Pocket'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5432:5432"
    networks:
      - net
  api:
    build:
      context: .
      dockerfile: Application/Dockerfile
    ports:
      - '5000:5000'
      - '5001:5001'
    depends_on:
      - postgres
    networks:
      - net
  web:
    build: ./Web
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
    ports:
      - '3000:3000'
      - '3001:3001'
    networks:
      - net  
networks: 
  net:
    driver: bridge    