version: "3.9"
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=Pocket
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - 5433:5432
    networks:
      - net
  api:
    build:
      context: .
      dockerfile: Application/Dockerfile     
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Server=postgres;Port=5433;Database=Pocket;User ID=postgres;Password=postgres;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - postgres
    networks:
      - net
    volumes: 
      - ${USERPROFILE}\.microsoft\usersecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/https/
      - ${USERPROFILE}\.aspnet\DataProtection-Keys\:/root/.aspnet/DataProtection-Keys
  web:
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - net
networks: 
  net:
    driver: bridge    