version: "3.9"
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB='Pocket'
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='postgres'
    ports:
      - '5432:5432'
    networks:
      - net
  api:
    build:
      context: .
      dockerfile: Application/Dockerfile     
    ports:
      - '5000:5000'
      - '5001:5001'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=host=postgres;port=5432;database=Pocket;username=postgres;password=postgres
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - postgres
    networks:
      - net
    volumes: 
      - ${USERPROFILE}\.microsoft\usersecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/https/
      - ${USERPROFILE}\.aspnet\DataProtection-Keys\:/root/.aspnet/DataProtection-Keys
  web:
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
    depends_on:
      - api
    networks:
      - net
    environment:
      - ROOT_API_URL=https://api:5001/api
networks: 
  net:
    driver: bridge    