version: "3.9"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: 'Pocket'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    networks:
      - net
  api:
    build:
      context: .
      dockerfile: Application/Dockerfile     
    ports:
      - '5000:80'
    environment: 
      DB_CONNECTION_STRING: 'host=postgres;port=5432;database=Pocket;username=postgres;password=postgres'
      DOTNET_URLS: https://localhost:5001;http://localhost:5004
    depends_on:
      - postgres
    networks:
      - net
    volumes: 
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
  web:
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
    depends_on:
      - api
    networks:
      - net  
networks: 
  net:
    driver: bridge    